In [2]:
import pandas as pd

In [3]:
def read_tsv(path: str) -> pd.DataFrame:
    return pd.read_csv(path, sep="\t", header=None)

In [5]:
var = read_tsv("../../data/features.tsv.gz")
var

                     0         1                2                 3     4
0      ENSG00000225602  MTOR-AS1  Gene Expression  Exonic (h.ens90)   705
1      ENSG00000171819   ANGPTL7  Gene Expression  Exonic (h.ens90)  2238
2      ENSG00000238173   RPL39P6  Gene Expression  Exonic (h.ens90)   150
3      ENSG00000239149  SNORA59A  Gene Expression  Exonic (h.ens90)   152
4      ENSG00000204518   AADACL4  Gene Expression  Exonic (h.ens90)  1575
...                ...       ...              ...               ...   ...
43745  ENSG00000211459   MT-RNR1  Gene Expression     Exonic (Mito)   954
43746  ENSG00000210077     MT-TV  Gene Expression     Exonic (Mito)    69
43747  ENSG00000210082   MT-RNR2  Gene Expression     Exonic (Mito)  1559
43748  ENSG00000209082    MT-TL1  Gene Expression     Exonic (Mito)    75
43749  ENSG00000198888    MT-ND1  Gene Expression     Exonic (Mito)   956

[43750 rows x 5 columns]

In [7]:
var.index = var.iloc[:, 1]
var

                        0         1                2                 3     4
1
MTOR-AS1  ENSG00000225602  MTOR-AS1  Gene Expression  Exonic (h.ens90)   705
ANGPTL7   ENSG00000171819   ANGPTL7  Gene Expression  Exonic (h.ens90)  2238
RPL39P6   ENSG00000238173   RPL39P6  Gene Expression  Exonic (h.ens90)   150
SNORA59A  ENSG00000239149  SNORA59A  Gene Expression  Exonic (h.ens90)   152
AADACL4   ENSG00000204518   AADACL4  Gene Expression  Exonic (h.ens90)  1575
...                   ...       ...              ...               ...   ...
MT-RNR1   ENSG00000211459   MT-RNR1  Gene Expression     Exonic (Mito)   954
MT-TV     ENSG00000210077     MT-TV  Gene Expression     Exonic (Mito)    69
MT-RNR2   ENSG00000210082   MT-RNR2  Gene Expression     Exonic (Mito)  1559
MT-TL1    ENSG00000209082    MT-TL1  Gene Expression     Exonic (Mito)    75
MT-ND1    ENSG00000198888    MT-ND1  Gene Expression     Exonic (Mito)   956

[43750 rows x 5 columns]

In [8]:
var = var.drop(columns=[var.columns[1]]) 
var

                        0                2                 3     4
1
MTOR-AS1  ENSG00000225602  Gene Expression  Exonic (h.ens90)   705
ANGPTL7   ENSG00000171819  Gene Expression  Exonic (h.ens90)  2238
RPL39P6   ENSG00000238173  Gene Expression  Exonic (h.ens90)   150
SNORA59A  ENSG00000239149  Gene Expression  Exonic (h.ens90)   152
AADACL4   ENSG00000204518  Gene Expression  Exonic (h.ens90)  1575
...                   ...              ...               ...   ...
MT-RNR1   ENSG00000211459  Gene Expression     Exonic (Mito)   954
MT-TV     ENSG00000210077  Gene Expression     Exonic (Mito)    69
MT-RNR2   ENSG00000210082  Gene Expression     Exonic (Mito)  1559
MT-TL1    ENSG00000209082  Gene Expression     Exonic (Mito)    75
MT-ND1    ENSG00000198888  Gene Expression     Exonic (Mito)   956

[43750 rows x 4 columns]

In [ ]:
# gene name to index map

gene_index = {name: i for i, name in enumerate(var.index)}
gene_index

{'MTOR-AS1': 0,
 'ANGPTL7': 1,
 'RPL39P6': 2,
 'SNORA59A': 3,
 'AADACL4': 4,
 'AC244670.1': 5,
 'AADACL3': 6,
 'PRAMEF5': 7,
 'OR4G11P': 8,
 'C1orf158': 9,
 'PRAMEF12': 10,
 'PRAMEF20': 11,
 'AL354712.1': 12,
 'RPL7P11': 13,
 'AL357552.1': 14,
 'RPL23AP19': 15,
 'ENO1-AS1': 16,
 'HMGN2P17': 17,
 'NPPA-AS1': 18,
 'AL021155.1': 19,
 'TBC1D3P6': 20,
 'C1orf64': 21,
 'CLCNKA': 22,
 'CLCNKB': 23,
 'AL451042.2': 24,
 'BX284668.2': 25,
 'BX284668.4': 26,
 'LINC01134': 27,
 'LINC01346': 28,
 'AL805961.1': 29,
 'LINC01777': 30,
 'LINC01646': 31,
 'AL669831.5': 32,
 'AJAP1': 33,
 'BX005132.1': 34,
 'Z98259.1': 35,
 'ACTRT2': 36,
 'PRDM16': 37,
 'AL512383.1': 38,
 'AL390719.1': 39,
 'LINC01342': 40,
 'AL137802.2': 41,
 'AL137802.1': 42,
 'MST1P2': 43,
 'PLA2G5': 44,
 'PLA2G2F': 45,
 'Z98257.1': 46,
 'UBXN10': 47,
 'LINC01757': 48,
 'AL136529.1': 49,
 'ACTL8': 50,
 'AL357509.1': 51,
 'LINC01654': 52,
 'IGSF21': 53,
 'AL031005.1': 54,
 'AL031728.1': 55,
 'PPP1R11P1': 56,
 'AL049569.1': 57,
 'AL590644.1': 58,
 'PADI1': 59,
 'PADI3': 60,
 'LDLRAD2': 61,
 'AL590556.1': 62,
 'CELA3B': 63,
 'Z98257.2': 64,
 'VWA5B1': 65,
 'AL139254.2': 66,
 'RPS4XP4': 67,
 'FAM43B': 68,
 'ESPN': 69,
 'AL591866.1': 70,
 'TAS1R1': 71,
 'ZBTB48': 72,
 'ZBTB40-IT1': 73,
 'EPHA8': 74,
 'C1QC': 75,
 'C1QB': 76,
 'MIB2': 77,
 'MMP23B': 78,
 'FO704657.1': 79,
 'AL691432.1': 80,
 'CCDC27': 81,
 'SMIM1': 82,
 'RN7SL574P': 83,
 'AL365330.1': 84,
 'DFFB': 85,
 'AL365209.1': 86,
 'KLHDC7A': 87,
 'DYNLL1P3': 88,
 'AL031737.1': 89,
 'CROCC': 90,
 'RNU6-135P': 91,
 'AL109936.1': 92,
 'AL109936.8': 93,
 'ZNF436-AS1': 94,
 'PADI4': 95,
 'PADI6': 96,
 'AC004824.1': 97,
 'ARHGEF10L': 98,
 'LINC01128': 99,
 'TUBB8P11': 100,
 'AL645608.7': 101,
 'AL645608.3': 102,
 'AL645608.5': 103,
 'MZT1P1': 104,
 'AL357140.1': 105,
 'AL357140.2': 106,
 'NMNAT1': 107,
 'RN7SKP269': 108,
 'LINC01714': 109,
 'SLC45A1': 110,
 'Y_RNA': 43553,
 'AL096855.1': 112,
 'AL096855.2': 113,
 'CELA3A': 114,
 'LINC00339': 115,
 'KCNAB2': 116,
 'RNF207': 117,
 'LINC00337': 118,
 'AL031848.2': 119,
 'SNRPFP2': 120,
 'SCARNA17': 121,
 'HS6ST1P1': 122,
 'CROCCP5': 123,
 'NBPF3': 124,
 'ALPL': 125,
 'AL359815.1': 126,
 'TNFRSF14': 127,
 'AL139246.3': 128,
 'FAM213B': 129,
 'AL831784.1': 130,
 'AL031282.1': 131,
 'AL109917.1': 132,
 'CALML6': 133,
 'GABRD': 134,
 'PRKCZ': 135,
 'AL354956.1': 136,
 'PEX14': 137,
 'RN7SL614P': 138,
 'AL139423.1': 139,
 'AL391244.1': 140,
 'AL391244.3': 141,
 'AL391244.2': 142,
 'VWA1': 143,
 'AL139415.2': 144,
 'CA6': 145,
 'LINC01759': 146,
 'H6PD': 147,
 'AL390719.2': 148,
 'TTLL10': 149,
 'B3GALT6': 150,
 'LINC01786': 151,
 'ARHGEF16': 152,
 'AL512413.1': 153,
 'TPRG1L': 154,
 'TP73': 155,
 'ACTG1P20': 156,
 'SYTL1': 157,
 'GPR3': 158,
 'FO393419.2': 159,
 'CD52': 160,
 'AL451139.1': 161,
 'LIN28A': 162,
 'DHDDS': 163,
 'HMGN2': 164,
 'SCNN1D': 165,
 'PUSL1': 166,
 'CPTP': 167,
 'TAS1R3': 168,
 'NDUFB4P8': 169,
 'ATAD3C': 170,
 'ATAD3B': 171,
 'AL645728.2': 172,
 'ATAD3A': 173,
 'AL645728.1': 174,
 'CDA': 175,
 'PINK1': 176,
 'AL663074.1': 177,
 'UBIAD1': 178,
 'DISP3': 179,
 'AL031731.1': 180,
 'FBXO44': 181,
 'EXTL1': 182,
 'AL391650.2': 183,
 'PDIK1L': 184,
 'FAM110D': 185,
 'ZNF593': 186,
 'BX293535.1': 187,
 'AL031729.1': 188,
 'AL445490.1': 189,
 'FAM76A': 190,
 'AL161638.1': 191,
 'MATN1-AS1': 192,
 'LINC01778': 193,
 'PNRC2': 194,
 'AL591178.1': 195,
 'AL591178.2': 196,
 'AL590683.1': 197,
 'GRHL3': 198,
 'LINC01225': 199,
 'LINC01226': 200,
 'TINAGL1': 201,
 'HCRTR1': 202,
 'AC114488.2': 203,
 'AL020997.1': 204,
 'RPEP3': 205,
 'STX12': 206,
 'AL020997.2': 207,
 'AL020997.3': 208,
 'TNFRSF8': 209,
 'TNFRSF1B': 210,
 'VPS13D': 211,
 'Metazoa_SRP': 43592,
 'AL590729.1': 213,
 'PTPRU': 214,
 'AL645944.2': 215,
 'AL137076.1': 216,
 'SAMD11': 217,
 'KLHL17': 218,
 'PLEKHN1': 219,
 'ISG15': 220,
 'AGRN': 221,
 'FBXO6': 222,
 'DRAXIN': 223,
 'AGTRAP': 224,
 'C1orf167': 225,
 'CLCN6': 226,
 'RBP7': 227,
 'UBE4B': 228,
 'PGAM1P11': 229,
 'PLEKHM2': 230,
 'SLC25A34': 231,
 'TMEM82': 232,
 'FBLIM1': 233,
 'AL031284.1': 234,
 'TMEM57': 235,
 'LDLRAP1': 236,
 'AL606491.1': 237,
 'MAN1C1': 238,
 'HSPD1P14': 239,
 'HMGB4': 240,
 'CSMD2-AS1': 241,
 'C1orf94': 242,
 'AL513327.3': 243,
 'AL513327.1': 244,
 'AL513327.2': 245,
 'TLR12P': 246,
 'ZSCAN20': 247,
 'GJB5': 248,
 'GJB4': 249,
 'GJB3': 250,
 'GJA4': 251,
 'RAB42': 252,
 'LINC01715': 253,
 'GMEB1': 254,
 'PHF13': 255,
 'THAP3': 256,
 'LINC01672': 257,
 'AL591163.1': 258,
 'CAMTA1': 259,
 'WDTC1': 260,
 'TMEM222': 261,
 'SPSB1': 262,
 'SLC25A33': 263,
 'AL954705.1': 264,
 'TMEM201': 265,
 'PIK3CD': 266,
 'SH3D21': 267,
 'AL591845.1': 268,
 'AL596257.1': 269,
 'AC117945.1': 270,
 'AL020995.1': 271,
 'AZIN2': 272,
 'AL662907.2': 273,
 'AL662907.3': 274,
 'ZNF362': 275,
 'NBL1': 276,
 'HTR6': 277,
 'AL391883.1': 278,
 'OTUD3': 279,
 'RN7SL304P': 280,
 'AL929472.2': 281,
 'SNORA63': 9515,
 'RNU6-510P': 284,
 'FTH1P1': 285,
 'AL034379.1': 286,
 'DNALI1': 287,
 'AL513220.1': 288,
 'CELA2B': 289,
 'DNAJC16': 290,
 'SCARNA21B': 291,
 'CHCHD2P6': 292,
 'DDI2': 293,
 'PPP1R8': 294,
 'SCARNA1': 295,
 'THEMIS2': 296,
 'SMPDL3B': 297,
 'S100PBP': 298,
 'HPCA': 299,
 'AL031602.1': 300,
 'AL355864.1': 301,
 'SNORA62': 17875,
 'RPL5P4': 303,
 'AC004865.1': 305,
 'NCDN': 306,
 'BRWD1P1': 307,
 'PDPN': 308,
 'PRDM2': 309,
 'KAZN': 310,
 'TMEM51': 311,
 'AL031430.1': 312,
 'ZC3H12A': 313,
 'TARDBP': 314,
 'AL109811.4': 315,
 'AL109811.3': 316,
 'AL109811.1': 317,
 'AL109811.2': 318,
 'AL031985.1': 319,
 'ZFP69B': 320,
 'AL031985.3': 321,
 'ZFP69': 322,
 'SELENON': 323,
 'AL020996.2': 324,
 'MTFR1L': 325,
 'AL033528.2': 326,
 'SLFNL1-AS1': 328,
 'RPL23AP17': 329,
 'AC093151.3': 330,
 'FOXO6': 331,
 'AL391094.1': 332,
 'FHAD1': 333,
 'EFHD2': 334,
 'CTRC': 335,
 'CELA2A': 336,
 'AL445235.1': 337,
 'AL356320.2': 338,
 'AL356320.1': 339,
 'ZCCHC17': 340,
 'SERINC2': 341,
 'CAMTA1-IT1': 342,
 'VAMP3': 343,
 'Z98884.2': 344,
 'PER3': 345,
 'PAX7': 346,
 'AL035413.1': 347,
 'MRTO4': 348,
 'AL035413.2': 349,
 'PQLC2': 350,
 'CNKSR1': 351,
 'CATSPER4': 352,
 'AL355877.1': 353,
 'CEP85': 354,
 'SH3BGRL3': 355,
 'RNU6-828P': 356,
 'KIF1B': 357,
 'RNU6-37P': 358,
 'HNRNPFP1': 359,
 'GUCA2B': 360,
 'RIMKLA': 361,
 'AL161637.1': 362,
 'FAM183A': 363,
 'CFAP57': 364,
 'AL445648.1': 365,
 'CLIC4': 366,
 'AL031432.1': 367,
 'ST3GAL3': 368,
 'U6': 25597,
 'ARTN': 370,
 'TMEM269': 371,
 'ERMAP': 372,
 'ZNF691': 373,
 'ATP6V1E1P1': 374,
 'SLC2A1-AS1': 375,
 'AL031432.4': 376,
 'AL031432.5': 377,
 'AL031432.3': 378,
 'RHD': 379,
 'TMEM50A': 380,
 'SNHG3': 381,
 'SNORA73B': 382,
 'AL513497.1': 383,
 'TRNAU1AP': 384,
 'AL035404.2': 385,
 'PPIE': 386,
 'AL035404.1': 387,
 'AL033527.3': 388,
 'AL033527.5': 389,
 'AL358075.1': 390,
 'AL358075.3': 391,
 'AL358075.2': 392,
 'TSPAN1': 393,
 'LURAP1': 394,
 'RNU5E-1': 395,
 'PLOD1': 396,
 'MFN2': 397,
 'MIIP': 398,
 'HDAC1': 399,
 'TSSK3': 400,
 'AL033529.1': 401,
 'FAAHP1': 402,
 'DMBX1': 403,
 'MKNK1-AS1': 404,
 'TEX38': 405,
 'EFCAB14-AS1': 406,
 'AL593856.1': 407,
 'CYP4B1': 408,
 'CYP4X1': 409,
 'CYP4Z1': 410,
 'RNU4-28P': 411,
 'MINOS1': 412,
 'MINOS1-NBL1': 413,
 'AL031727.1': 414,
 'AL109659.1': 415,
 'SLC5A9': 416,
 'AL451042.1': 417,
 'ARHGEF19-AS1': 418,
 'SZRD1': 419,
 'NECAP2': 420,
 'LINC01772': 421,
 'XKR8': 422,
 'ATPIF1': 423,
 'SESN2': 424,
 'FOXD2': 425,
 'LINC01738': 426,
 'AC096541.1': 427,
 'AL356289.1': 428,
 'MTND2P29': 429,
 'ELAVL4': 430,
 'AL583843.1': 431,
 'AL592182.3': 432,
 'ELOA': 433,
 'PITHD1': 434,
 'LYPLA2': 435,
 'AL596275.1': 436,
 'AL049637.2': 437,
 'AL049637.1': 438,
 'RNU6-1026P': 439,
 'PHBP12': 440,
 'AL050343.2': 441,
 'AL445685.2': 442,
 'AL356968.2': 443,
 'AC092264.1': 444,
 'AL590432.1': 445,
 'ZNF859P': 446,
 'BTBD19': 447,
 'RNA5SP47': 448,
 'CCNB1IP1P1': 449,
 'UROD': 450,
 'LINC01144': 451,
 'AL591167.1': 452,
 'EEF1GP7': 453,
 'GPX7': 454,
 'FAM159A': 455,
 'NDUFS5P3': 456,
 'AL590822.1': 457,
 'SKI': 458,
 'RER1': 459,
 'PLCH2': 460,
 'AL139246.5': 461,
 'MTND1P23': 462,
 'MTND2P28': 463,
 'UTP11': 464,
 'AL139158.2': 465,
 'LINC01685': 466,
 'AL606760.1': 467,
 'AL355483.4': 468,
 'AL355483.2': 469,
 'AL355483.3': 470,
 'LINC01771': 471,
 'PPCS': 472,
 'CCDC30': 473,
 'AL445669.1': 474,
 'RPS6KA1': 475,
 'ARID1A': 476,
 'PIGV': 477,
 'EXO5': 478,
 'ZNF684': 479,
 'NFYC': 480,
 'PODN': 481,
 'AL445183.2': 482,
 'AL606760.4': 483,
 'CPT2': 484,
 'AL606760.3': 485,
 'YTHDF2': 486,
 'OPRD1': 487,
 'EPB41': 488,
 'TFAP2E': 489,
 'AL354864.1': 490,
 'AGO4': 491,
 'AGO1': 492,
 'AGO3': 493,
 'MIR4422HG': 494,
 'GYG1P3': 495,
 'GOT2P1': 496,
 'AL603840.1': 497,
 'LINC01755': 498,
 'AL353681.1': 499,
 'LINC01767': 500,
 'RPL21P23': 501,
 'AL161644.1': 502,
 'AL035415.1': 503,
 'AC099796.2': 504,
 'HNRNPA1P63': 505,
 'ACOT11': 506,
 'AC096536.1': 507,
 'TMEM61': 508,
 'BSND': 509,
 'PCSK9': 510,
 'AL445193.2': 511,
 'AL445193.1': 512,
 'AL136985.3': 513,
 'LINC01135': 514,
 'LINC01358': 515,
 'LAMTOR5P1': 516,
 'RN7SL180P': 517,
 'AL009183.1': 518,
 'PARK7': 519,
 'AL034417.4': 520,
 'AL034417.2': 521,
 'AL358876.1': 522,
 'AL139220.2': 523,
 'KLF17': 524,
 'DMAP1': 525,
 'RNF220': 526,
 'AC096543.1': 527,
 'MRPS6P2': 528,
 'CDKN2C': 529,
 'C1orf185': 530,
 'MROH7-TTC4': 531,
 'TTC4': 532,
 'LEXM': 533,
 'PHBP3': 534,
 'FGGY': 535,
 'HOOK1': 536,
 'AC097066.1': 537,
 'RPL12P14': 538,
 'AL450998.1': 539,
 'SPEN': 540,
 'AL355994.4': 541,
 'AL355994.1': 542,
 'HPDL': 543,
 'TOE1': 544,
 'MMACHC': 545,
 'HMGB1P48': 546,
 'PRKAA2': 547,
 'C8A': 548,
 'AL161740.1': 549,
 'DAB1-AS1': 550,
 'IL12RB2': 551,
 'LINC01702': 552,
 'ANGPTL3': 553,
 'AL138847.2': 554,
 'AC103923.1': 555,
 'ATG4C': 556,
 'AC099794.1': 557,
 'DMRTB1': 558,
 'AL049745.1': 559,
 'DIO1': 560,
 'LRRC42': 561,
 'TCEANC2': 562,
 'EPHB2': 563,
 'KDM1A': 564,
 'AL161672.1': 565,
 'DEPDC1-AS1': 566,
 'LINC01707': 567,
 'LRRC7': 568,
 'FOXD3': 569,
 'ALG6': 570,
 'EFCAB7': 571,
 'DLEU2L': 572,
 'AL583808.2': 573,
 'KRT8P21': 574,
 'LINC01360': 575,
 'LINC02238': 576,
 'IQCC': 577,
 'DCDC2B': 578,
 'EIF3I': 579,
 'FAM167B': 580,
 'LCK': 581,
 'PDCL3P6': 582,
 'ANAPC10P1': 583,
 'AL513218.1': 584,
 'PLA2G12AP1': 585,
 'PRPF38A': 586,
 'AL354872.2': 587,
 'AL354872.1': 588,
 'LINC01788': 589,
 'AL031429.1': 590,
 'ZRANB2-AS1': 591,
 'MSH4': 592,
 'AC092813.1': 593,
 'AC092813.2': 594,
 'ST6GALNAC3': 595,
 'CDC42': 596,
 'CDC42-IT1': 597,
 'AL031281.2': 598,
 'ZBTB40': 599,
 'RNF11': 600,
 'TTC39A-AS1': 601,
 'AL671986.1': 602,
 'AC104458.1': 603,
 'TPI1P1': 604,
 'ST6GALNAC5': 605,
 'ZMYM1': 606,
 'EFCAB14P1': 607,
 'ZMYM4': 608,
 'ZRANB2-AS2': 609,
 'AL359821.1': 610,
 'GDI2P2': 611,
 'RPL31P12': 612,
 'AL035409.1': 613,
 'AC113935.1': 614,
 'AC093433.1': 615,
 'AK5': 616,
 'MGC27382': 617,
 'PTGFR': 618,
 'IFI44L': 619,
 'IFI44': 620,
 'HMGB1P18': 621,
 'AL596276.2': 622,
 'LINC01781': 623,
 'MTND2P30': 624,
 'AL357632.1': 625,
 'TMEM125': 626,
 'TIE1': 627,
 'MPL': 628,
 'CDC20': 629,
 'AL139289.1': 630,
 'AC104837.1': 631,
 'ADH5P2': 632,
 'AL445685.1': 633,
 'BTF3L4': 634,
 'ZFYVE9': 635,
 'RN7SL788P': 636,
 'CDCA8': 637,
 'ACTN4P2': 638,
 'MANEAL': 639,
 'C1orf122': 640,
 'AL359504.1': 641,
 'AL450063.1': 642,
 'SAMD13': 643,
 'NIPAL3': 644,
 'RCAN3': 645,
 'NCMAP': 646,
 'AL445686.1': 647,
 'SRRM1': 648,
 'RAVER2': 649,
 'AL606517.1': 650,
 'AK4': 651,
 'AC104455.1': 652,
 'CLCA2': 653,
 'CLCA1': 654,
 'CLCA4': 655,
 'AL445991.1': 656,
 'AC099063.4': 657,
 'AC099063.1': 658,
 'BX119321.1': 659,
 'GBP6': 660,
 'FPGT': 661,
 'FPGT-TNNI3K': 662,
 'TNNI3K': 663,
 'AC105271.1': 664,
 'ERICH3-AS1': 665,
 'AL353898.1': 666,
 'AL357673.2': 667,
 'MRPL37': 668,
 'SSBP3-AS1': 669,
 'LINC01763': 670,
 'RPL5P6': 671,
 'FEN1P1': 672,
 'KPNA6': 673,
 'TXLNA': 674,
 'CCDC28B': 675,
 'AC104170.2': 676,
 'AC104170.1': 677,
 'OSBPL9': 678,
 'SLC25A6P3': 679,
 'AL050343.1': 680,
 'LPCAT2BP': 681,
 'BTBD8': 682,
 'AC104836.1': 683,
 'PRKAR1AP1': 684,
 'ZBTB8B': 685,
 'ZBTB8A': 686,
 'RBBP4': 687,
 'KIAA1522': 688,
 'MED18': 689,
 'PHACTR4': 690,
 'CR391992.1': 691,
 'RNU6ATAC27P': 692,
 'RCC1': 693,
 'RN7SL62P': 694,
 'ZYG11B': 695,
 'ZYG11A': 696,
 'AC099677.1': 697,
 'AC119800.1': 698,
 'PDE4B': 699,
 'SGIP1': 700,
 'TCTEX1D1': 701,
 'AL049796.1': 702,
 'AC093579.1': 703,
 'AC097059.1': 704,
 'GAPDHP29': 705,
 'KCNQ4': 706,
 'AC119677.1': 707,
 'CTPS1': 708,
 'AL683887.1': 709,
 'AC099566.1': 710,
 'RNU1-130P': 711,
 'AC092393.1': 712,
 'UBE2WP1': 713,
 'GADD45A': 714,
 'GNG12-AS1': 715,
 'AL157407.1': 716,
 'AL138789.1': 717,
 'RPL26P9': 718,
 'AC114878.1': 719,
 'NFU1P2': 720,
 'MIER1': 721,
 'IL23R': 722,
 'AL389925.1': 723,
 'PALMD': 724,
 'HMGB3P10': 725,
 'SCP2': 726,
 'MIR1273F': 727,
 'MIR1273G': 728,
 'ADGRL2': 729,
 'HNRNPA3P14': 730,
 'AL138799.1': 731,
 'CDC7': 732,
 'HSP90B3P': 733,
 'BRDT': 734,
 'EPHX4': 735,
 'RLF': 736,
 'TMCO2': 737,
 'ZMPSTE24': 738,
 'SMAP2': 739,
 'TMEM56-RWDD3': 740,
 'AC092802.3': 741,
 'RWDD3': 742,
 'LINC01761': 743,
 'AL356479.1': 744,
 'LINC00853': 745,
 'AL135960.1': 746,
 'CMPK1': 747,
 'FOXE3': 748,
 'AL109741.2': 749,
 'LINC01307': 750,
 'LINC01709': 751,
 'AL356280.1': 752,
 'TYW3': 753,
 'LHX8': 754,
 'AC093156.1': 755,
 'AMY2A': 756,
 'AL357134.1': 757,
 'MDS2': 758,
 'AL451000.1': 759,
 'RPL11': 760,
 'AL355306.2': 761,
 'LINC01661': 762,
 'PRMT6': 763,
 'NTNG1': 764,
 'AC093157.1': 765,
 'AC119501.1': 766,
 'S1PR1': 767,
 'AL359258.3': 768,
 'SLC25A24P1': 769,
 'AC114491.1': 770,
 'VAV3-AS1': 771,
 'AL390036.1': 772,
 'AL359258.2': 773,
 'ST13P20': 774,
 'LINC01362': 775,
 'LINC01712': 776,
 'AL035706.1': 777,
 'PRKACB': 778,
 'MIGA1': 779,
 'NSRP1P1': 780,
 'DNASE2B': 781,
 'RPF1': 782,
 'SPATA1': 783,
 'WDR63': 784,
 'AL078459.1': 786,
 'AL360219.1': 787,
 'CYR61': 788,
 'SNORD81': 16562,
 'RPS15AP7': 790,
 'L1TD1': 791,
 'USP1': 792,
 'MTCO1P12': 793,
 'MTCO2P12': 794,
 'MTATP8P1': 795,
 'MTATP6P1': 796,
 'MTCO3P12': 797,
 'CAPNS1P1': 798,
 'GBP1P1': 799,
 'LRRC8B': 800,
 'AC093423.2': 801,
 'LRRC8C': 802,
 'DNAJA1P5': 803,
 'AC095032.2': 804,
 'RNPC3': 805,
 'AMY2B': 806,
 'RPL7P8': 807,
 'GSTM4': 808,
 'GSTM2': 809,
 'GSTM1': 810,
 'GSTM5': 811,
 'OR11I1P': 812,
 'CD53': 813,
 'AL360270.1': 814,
 'AL360270.3': 815,
 'PIFO': 816,
 'HIGD1AP12': 817,
 'UBE2FP3': 818,
 'AL355488.2': 820,
 'PROK1': 821,
 'AL358215.2': 822,
 'AL358215.3': 823,
 'CYMP': 824,
 'AC093155.1': 825,
 'LINC01140': 826,
 'AC099062.1': 827,
 'LMO4': 828,
 'HSPE1P25': 829,
 'NEXN': 830,
 'DNAJB4': 831,
 'GIPC2': 832,
 'AC103591.1': 833,
 'SZT2': 834,
 'HYI-AS1': 835,
 'PTPRF': 836,
 'KDM4A': 837,
 'RPL12P13': 838,
 'TRNP1': 839,
 'AL590640.2': 840,
 'NPM1P39': 841,
 'RANP5': 842,
 'TMEM167B': 843,
 'KIAA1324': 844,
 'IPO13': 845,
 'DPH2': 846,
 'ATP6V0B': 847,
 'B4GALT2': 848,
 'CCDC24': 849,
 'NR1H5P': 850,
 'SYCP1': 851,
 'TSHB': 852,
 'AC093019.1': 853,
 'TRMT13': 854,
 'RPL23AP90': 855,
 'BRI3P1': 856,
 'AL445928.1': 857,
 'PGM1': 858,
 'RN7SL130P': 859,
 'ROR1': 860,
 'UBE2U': 861,
 'CACHD1': 862,
 'AL136455.1': 863,
 'AC092506.1': 864,
 'CDK4P1': 865,
 'SEPT2P1': 866,
 'AL512844.1': 867,
 'AL512638.2': 868,
 'AL512638.1': 869,
 'ELOCP20': 870,
 'CNOT7P2': 871,
 'AL354702.1': 872,
 'AL139260.1': 873,
 'RNU6-605P': 874,
 'AKIRIN1': 875,
 'NDUFS5': 876,
 'AL033527.2': 877,
 'MFSD2A': 878,
 'AL663070.1': 879,
 'CAP1': 880,
 'AL512599.1': 881,
 'PLK3': 882,
 'HSD3B2': 883,
 'HSD3BP2': 884,
 'HSD3BP1': 885,
 'HSD3B1': 886,
 'HSD3BP3': 887,
 'STRIP1': 888,
 'AL160006.1': 889,
 'LINC01397': 890,
 'UBL4B': 891,
 'SLC6A17': 892,
 'MACF1': 893,
 'AL356055.1': 894,
 'BMP8A': 895,
 'OXCT2P1': 896,
 'AL365277.2': 897,
 'AL035410.2': 898,
 'AL035410.1': 899,
 'EIF2S2P5': 900,
 'PKMP1': 901,
 'NBPF26': 902,
 'PPIAL4A': 903,
 'LINC00623': 904,
 'EEF1A1P11': 905,
 'PTBP2': 906,
 'DPYD-AS1': 907,
 'SEC63P1': 908,
 'AC244021.2': 909,
 'AL592494.2': 910,
 'EMBP1': 911,
 'AC244669.2': 912,
 'NBPF8': 913,
 'AC239859.1': 914,
 'PFN1P12': 915,
 'LINC01776': 916,
 'SNX7': 917,
 'AL445433.2': 918,
 'AL445433.1': 919,
 'PLPPR4': 920,
 'WARS2-IT1': 921,
 'AL359915.2': 922,
 'LINC01780': 923,
 'HAO2': 924,
 'AC239800.2': 925,
 'AC239800.1': 926,
 'FAM91A3P': 927,
 'AC239800.3': 928,
 'AC241585.1': 929,
 'AC239799.2': 930,
 'FP700111.1': 931,
 'FP700107.1': 932,
 'FAM72D': 933,
 'LINC01750': 934,
 'TXNP3': 935,
 'CTTNBP2NL': 936,
 'AL139424.2': 937,
 'PGD': 938,
 'CENPS-CORT': 939,
 'CENPS': 940,
 'CORT': 941,
 'AC114488.3': 942,
 'AL136115.1': 943,
 'KHDRBS1': 944,
 'TMEM39B': 945,
 'PPIH': 946,
 'AC098484.2': 947,
 'YBX1': 948,
 'C1orf50': 949,
 'AC098484.3': 950,
 'PDE4DIPP1': 951,
 'ABHD17AP1': 952,
 'AC239803.1': 953,
 'AC245100.6': 954,
 'AC245100.1': 955,
 'GPR89A': 956,
 'HYDIN2': 957,
 'NBPF12': 958,
 'AC244394.1': 959,
 'GPR89B': 960,
 'AC239803.2': 961,
 'AC239803.3': 962,
 'AC245100.8': 963,
 'U1': 3175,
 'RAD54L': 965,
 'UQCRH': 966,
 'NSUN4': 967,
 'AL122001.1': 968,
 'FAAH': 969,
 'AC104836.2': 970,
 'AL663109.1': 971,
 'C1orf146': 972,
 'RPAP2': 973,
 'AC104332.1': 974,
 'AC245100.4': 975,
 'RNVU1-3': 976,
 'AC245100.2': 977,
 'AL449283.1': 978,
 'MTF2': 979,
 'CCDC18': 980,
 'HIST2H4A': 981,
 'AC239868.1': 982,
 'AC239868.4': 983,
 'AC244453.1': 984,
 'SRGAP2C': 985,
 'AC244021.1': 986,
 'CEPT1': 987,
 'CHI3L2': 988,
 'CHIAP1': 989,
 'CHIAP2': 990,
 'CHIA': 991,
 'HSD3BP4': 992,
 'PHGDH': 993,
 'PFN1P9': 994,
 'RTCA': 995,
 'CDC14A': 996,
 'GPR88': 997,
 'BCL9': 998,
 'AC241644.2': 999,
 'AL096829.1': 1000,
 'ACADM': 1001,
 'RABGGTB': 1002,
 'ADAMTSL4': 1003,
 'RNU6-1042P': 1004,
 ...}

In [12]:
# index to gene map

index_gene = {i: name for i, name in enumerate(var.index)}
index_gene

{0: 'MTOR-AS1',
 1: 'ANGPTL7',
 2: 'RPL39P6',
 3: 'SNORA59A',
 4: 'AADACL4',
 5: 'AC244670.1',
 6: 'AADACL3',
 7: 'PRAMEF5',
 8: 'OR4G11P',
 9: 'C1orf158',
 10: 'PRAMEF12',
 11: 'PRAMEF20',
 12: 'AL354712.1',
 13: 'RPL7P11',
 14: 'AL357552.1',
 15: 'RPL23AP19',
 16: 'ENO1-AS1',
 17: 'HMGN2P17',
 18: 'NPPA-AS1',
 19: 'AL021155.1',
 20: 'TBC1D3P6',
 21: 'C1orf64',
 22: 'CLCNKA',
 23: 'CLCNKB',
 24: 'AL451042.2',
 25: 'BX284668.2',
 26: 'BX284668.4',
 27: 'LINC01134',
 28: 'LINC01346',
 29: 'AL805961.1',
 30: 'LINC01777',
 31: 'LINC01646',
 32: 'AL669831.5',
 33: 'AJAP1',
 34: 'BX005132.1',
 35: 'Z98259.1',
 36: 'ACTRT2',
 37: 'PRDM16',
 38: 'AL512383.1',
 39: 'AL390719.1',
 40: 'LINC01342',
 41: 'AL137802.2',
 42: 'AL137802.1',
 43: 'MST1P2',
 44: 'PLA2G5',
 45: 'PLA2G2F',
 46: 'Z98257.1',
 47: 'UBXN10',
 48: 'LINC01757',
 49: 'AL136529.1',
 50: 'ACTL8',
 51: 'AL357509.1',
 52: 'LINC01654',
 53: 'IGSF21',
 54: 'AL031005.1',
 55: 'AL031728.1',
 56: 'PPP1R11P1',
 57: 'AL049569.1',
 58: 'AL590644.1',
 59: 'PADI1',
 60: 'PADI3',
 61: 'LDLRAD2',
 62: 'AL590556.1',
 63: 'CELA3B',
 64: 'Z98257.2',
 65: 'VWA5B1',
 66: 'AL139254.2',
 67: 'RPS4XP4',
 68: 'FAM43B',
 69: 'ESPN',
 70: 'AL591866.1',
 71: 'TAS1R1',
 72: 'ZBTB48',
 73: 'ZBTB40-IT1',
 74: 'EPHA8',
 75: 'C1QC',
 76: 'C1QB',
 77: 'MIB2',
 78: 'MMP23B',
 79: 'FO704657.1',
 80: 'AL691432.1',
 81: 'CCDC27',
 82: 'SMIM1',
 83: 'RN7SL574P',
 84: 'AL365330.1',
 85: 'DFFB',
 86: 'AL365209.1',
 87: 'KLHDC7A',
 88: 'DYNLL1P3',
 89: 'AL031737.1',
 90: 'CROCC',
 91: 'RNU6-135P',
 92: 'AL109936.1',
 93: 'AL109936.8',
 94: 'ZNF436-AS1',
 95: 'PADI4',
 96: 'PADI6',
 97: 'AC004824.1',
 98: 'ARHGEF10L',
 99: 'LINC01128',
 100: 'TUBB8P11',
 101: 'AL645608.7',
 102: 'AL645608.3',
 103: 'AL645608.5',
 104: 'MZT1P1',
 105: 'AL357140.1',
 106: 'AL357140.2',
 107: 'NMNAT1',
 108: 'RN7SKP269',
 109: 'LINC01714',
 110: 'SLC45A1',
 111: 'Y_RNA',
 112: 'AL096855.1',
 113: 'AL096855.2',
 114: 'CELA3A',
 115: 'LINC00339',
 116: 'KCNAB2',
 117: 'RNF207',
 118: 'LINC00337',
 119: 'AL031848.2',
 120: 'SNRPFP2',
 121: 'SCARNA17',
 122: 'HS6ST1P1',
 123: 'CROCCP5',
 124: 'NBPF3',
 125: 'ALPL',
 126: 'AL359815.1',
 127: 'TNFRSF14',
 128: 'AL139246.3',
 129: 'FAM213B',
 130: 'AL831784.1',
 131: 'AL031282.1',
 132: 'AL109917.1',
 133: 'CALML6',
 134: 'GABRD',
 135: 'PRKCZ',
 136: 'AL354956.1',
 137: 'PEX14',
 138: 'RN7SL614P',
 139: 'AL139423.1',
 140: 'AL391244.1',
 141: 'AL391244.3',
 142: 'AL391244.2',
 143: 'VWA1',
 144: 'AL139415.2',
 145: 'CA6',
 146: 'LINC01759',
 147: 'H6PD',
 148: 'AL390719.2',
 149: 'TTLL10',
 150: 'B3GALT6',
 151: 'LINC01786',
 152: 'ARHGEF16',
 153: 'AL512413.1',
 154: 'TPRG1L',
 155: 'TP73',
 156: 'ACTG1P20',
 157: 'SYTL1',
 158: 'GPR3',
 159: 'FO393419.2',
 160: 'CD52',
 161: 'AL451139.1',
 162: 'LIN28A',
 163: 'DHDDS',
 164: 'HMGN2',
 165: 'SCNN1D',
 166: 'PUSL1',
 167: 'CPTP',
 168: 'TAS1R3',
 169: 'NDUFB4P8',
 170: 'ATAD3C',
 171: 'ATAD3B',
 172: 'AL645728.2',
 173: 'ATAD3A',
 174: 'AL645728.1',
 175: 'CDA',
 176: 'PINK1',
 177: 'AL663074.1',
 178: 'UBIAD1',
 179: 'DISP3',
 180: 'AL031731.1',
 181: 'FBXO44',
 182: 'EXTL1',
 183: 'AL391650.2',
 184: 'PDIK1L',
 185: 'FAM110D',
 186: 'ZNF593',
 187: 'BX293535.1',
 188: 'AL031729.1',
 189: 'AL445490.1',
 190: 'FAM76A',
 191: 'AL161638.1',
 192: 'MATN1-AS1',
 193: 'LINC01778',
 194: 'PNRC2',
 195: 'AL591178.1',
 196: 'AL591178.2',
 197: 'AL590683.1',
 198: 'GRHL3',
 199: 'LINC01225',
 200: 'LINC01226',
 201: 'TINAGL1',
 202: 'HCRTR1',
 203: 'AC114488.2',
 204: 'AL020997.1',
 205: 'RPEP3',
 206: 'STX12',
 207: 'AL020997.2',
 208: 'AL020997.3',
 209: 'TNFRSF8',
 210: 'TNFRSF1B',
 211: 'VPS13D',
 212: 'Metazoa_SRP',
 213: 'AL590729.1',
 214: 'PTPRU',
 215: 'AL645944.2',
 216: 'AL137076.1',
 217: 'SAMD11',
 218: 'KLHL17',
 219: 'PLEKHN1',
 220: 'ISG15',
 221: 'AGRN',
 222: 'FBXO6',
 223: 'DRAXIN',
 224: 'AGTRAP',
 225: 'C1orf167',
 226: 'CLCN6',
 227: 'RBP7',
 228: 'UBE4B',
 229: 'PGAM1P11',
 230: 'PLEKHM2',
 231: 'SLC25A34',
 232: 'TMEM82',
 233: 'FBLIM1',
 234: 'AL031284.1',
 235: 'TMEM57',
 236: 'LDLRAP1',
 237: 'AL606491.1',
 238: 'MAN1C1',
 239: 'HSPD1P14',
 240: 'HMGB4',
 241: 'CSMD2-AS1',
 242: 'C1orf94',
 243: 'AL513327.3',
 244: 'AL513327.1',
 245: 'AL513327.2',
 246: 'TLR12P',
 247: 'ZSCAN20',
 248: 'GJB5',
 249: 'GJB4',
 250: 'GJB3',
 251: 'GJA4',
 252: 'RAB42',
 253: 'LINC01715',
 254: 'GMEB1',
 255: 'PHF13',
 256: 'THAP3',
 257: 'LINC01672',
 258: 'AL591163.1',
 259: 'CAMTA1',
 260: 'WDTC1',
 261: 'TMEM222',
 262: 'SPSB1',
 263: 'SLC25A33',
 264: 'AL954705.1',
 265: 'TMEM201',
 266: 'PIK3CD',
 267: 'SH3D21',
 268: 'AL591845.1',
 269: 'AL596257.1',
 270: 'AC117945.1',
 271: 'AL020995.1',
 272: 'AZIN2',
 273: 'AL662907.2',
 274: 'AL662907.3',
 275: 'ZNF362',
 276: 'NBL1',
 277: 'HTR6',
 278: 'AL391883.1',
 279: 'OTUD3',
 280: 'RN7SL304P',
 281: 'AL929472.2',
 282: 'SNORA63',
 283: 'Metazoa_SRP',
 284: 'RNU6-510P',
 285: 'FTH1P1',
 286: 'AL034379.1',
 287: 'DNALI1',
 288: 'AL513220.1',
 289: 'CELA2B',
 290: 'DNAJC16',
 291: 'SCARNA21B',
 292: 'CHCHD2P6',
 293: 'DDI2',
 294: 'PPP1R8',
 295: 'SCARNA1',
 296: 'THEMIS2',
 297: 'SMPDL3B',
 298: 'S100PBP',
 299: 'HPCA',
 300: 'AL031602.1',
 301: 'AL355864.1',
 302: 'SNORA62',
 303: 'RPL5P4',
 304: 'Metazoa_SRP',
 305: 'AC004865.1',
 306: 'NCDN',
 307: 'BRWD1P1',
 308: 'PDPN',
 309: 'PRDM2',
 310: 'KAZN',
 311: 'TMEM51',
 312: 'AL031430.1',
 313: 'ZC3H12A',
 314: 'TARDBP',
 315: 'AL109811.4',
 316: 'AL109811.3',
 317: 'AL109811.1',
 318: 'AL109811.2',
 319: 'AL031985.1',
 320: 'ZFP69B',
 321: 'AL031985.3',
 322: 'ZFP69',
 323: 'SELENON',
 324: 'AL020996.2',
 325: 'MTFR1L',
 326: 'AL033528.2',
 327: 'Y_RNA',
 328: 'SLFNL1-AS1',
 329: 'RPL23AP17',
 330: 'AC093151.3',
 331: 'FOXO6',
 332: 'AL391094.1',
 333: 'FHAD1',
 334: 'EFHD2',
 335: 'CTRC',
 336: 'CELA2A',
 337: 'AL445235.1',
 338: 'AL356320.2',
 339: 'AL356320.1',
 340: 'ZCCHC17',
 341: 'SERINC2',
 342: 'CAMTA1-IT1',
 343: 'VAMP3',
 344: 'Z98884.2',
 345: 'PER3',
 346: 'PAX7',
 347: 'AL035413.1',
 348: 'MRTO4',
 349: 'AL035413.2',
 350: 'PQLC2',
 351: 'CNKSR1',
 352: 'CATSPER4',
 353: 'AL355877.1',
 354: 'CEP85',
 355: 'SH3BGRL3',
 356: 'RNU6-828P',
 357: 'KIF1B',
 358: 'RNU6-37P',
 359: 'HNRNPFP1',
 360: 'GUCA2B',
 361: 'RIMKLA',
 362: 'AL161637.1',
 363: 'FAM183A',
 364: 'CFAP57',
 365: 'AL445648.1',
 366: 'CLIC4',
 367: 'AL031432.1',
 368: 'ST3GAL3',
 369: 'U6',
 370: 'ARTN',
 371: 'TMEM269',
 372: 'ERMAP',
 373: 'ZNF691',
 374: 'ATP6V1E1P1',
 375: 'SLC2A1-AS1',
 376: 'AL031432.4',
 377: 'AL031432.5',
 378: 'AL031432.3',
 379: 'RHD',
 380: 'TMEM50A',
 381: 'SNHG3',
 382: 'SNORA73B',
 383: 'AL513497.1',
 384: 'TRNAU1AP',
 385: 'AL035404.2',
 386: 'PPIE',
 387: 'AL035404.1',
 388: 'AL033527.3',
 389: 'AL033527.5',
 390: 'AL358075.1',
 391: 'AL358075.3',
 392: 'AL358075.2',
 393: 'TSPAN1',
 394: 'LURAP1',
 395: 'RNU5E-1',
 396: 'PLOD1',
 397: 'MFN2',
 398: 'MIIP',
 399: 'HDAC1',
 400: 'TSSK3',
 401: 'AL033529.1',
 402: 'FAAHP1',
 403: 'DMBX1',
 404: 'MKNK1-AS1',
 405: 'TEX38',
 406: 'EFCAB14-AS1',
 407: 'AL593856.1',
 408: 'CYP4B1',
 409: 'CYP4X1',
 410: 'CYP4Z1',
 411: 'RNU4-28P',
 412: 'MINOS1',
 413: 'MINOS1-NBL1',
 414: 'AL031727.1',
 415: 'AL109659.1',
 416: 'SLC5A9',
 417: 'AL451042.1',
 418: 'ARHGEF19-AS1',
 419: 'SZRD1',
 420: 'NECAP2',
 421: 'LINC01772',
 422: 'XKR8',
 423: 'ATPIF1',
 424: 'SESN2',
 425: 'FOXD2',
 426: 'LINC01738',
 427: 'AC096541.1',
 428: 'AL356289.1',
 429: 'MTND2P29',
 430: 'ELAVL4',
 431: 'AL583843.1',
 432: 'AL592182.3',
 433: 'ELOA',
 434: 'PITHD1',
 435: 'LYPLA2',
 436: 'AL596275.1',
 437: 'AL049637.2',
 438: 'AL049637.1',
 439: 'RNU6-1026P',
 440: 'PHBP12',
 441: 'AL050343.2',
 442: 'AL445685.2',
 443: 'AL356968.2',
 444: 'AC092264.1',
 445: 'AL590432.1',
 446: 'ZNF859P',
 447: 'BTBD19',
 448: 'RNA5SP47',
 449: 'CCNB1IP1P1',
 450: 'UROD',
 451: 'LINC01144',
 452: 'AL591167.1',
 453: 'EEF1GP7',
 454: 'GPX7',
 455: 'FAM159A',
 456: 'NDUFS5P3',
 457: 'AL590822.1',
 458: 'SKI',
 459: 'RER1',
 460: 'PLCH2',
 461: 'AL139246.5',
 462: 'MTND1P23',
 463: 'MTND2P28',
 464: 'UTP11',
 465: 'AL139158.2',
 466: 'LINC01685',
 467: 'AL606760.1',
 468: 'AL355483.4',
 469: 'AL355483.2',
 470: 'AL355483.3',
 471: 'LINC01771',
 472: 'PPCS',
 473: 'CCDC30',
 474: 'AL445669.1',
 475: 'RPS6KA1',
 476: 'ARID1A',
 477: 'PIGV',
 478: 'EXO5',
 479: 'ZNF684',
 480: 'NFYC',
 481: 'PODN',
 482: 'AL445183.2',
 483: 'AL606760.4',
 484: 'CPT2',
 485: 'AL606760.3',
 486: 'YTHDF2',
 487: 'OPRD1',
 488: 'EPB41',
 489: 'TFAP2E',
 490: 'AL354864.1',
 491: 'AGO4',
 492: 'AGO1',
 493: 'AGO3',
 494: 'MIR4422HG',
 495: 'GYG1P3',
 496: 'GOT2P1',
 497: 'AL603840.1',
 498: 'LINC01755',
 499: 'AL353681.1',
 500: 'LINC01767',
 501: 'RPL21P23',
 502: 'AL161644.1',
 503: 'AL035415.1',
 504: 'AC099796.2',
 505: 'HNRNPA1P63',
 506: 'ACOT11',
 507: 'AC096536.1',
 508: 'TMEM61',
 509: 'BSND',
 510: 'PCSK9',
 511: 'AL445193.2',
 512: 'AL445193.1',
 513: 'AL136985.3',
 514: 'LINC01135',
 515: 'LINC01358',
 516: 'LAMTOR5P1',
 517: 'RN7SL180P',
 518: 'AL009183.1',
 519: 'PARK7',
 520: 'AL034417.4',
 521: 'AL034417.2',
 522: 'AL358876.1',
 523: 'AL139220.2',
 524: 'KLF17',
 525: 'DMAP1',
 526: 'RNF220',
 527: 'AC096543.1',
 528: 'MRPS6P2',
 529: 'CDKN2C',
 530: 'C1orf185',
 531: 'MROH7-TTC4',
 532: 'TTC4',
 533: 'LEXM',
 534: 'PHBP3',
 535: 'FGGY',
 536: 'HOOK1',
 537: 'AC097066.1',
 538: 'RPL12P14',
 539: 'AL450998.1',
 540: 'SPEN',
 541: 'AL355994.4',
 542: 'AL355994.1',
 543: 'HPDL',
 544: 'TOE1',
 545: 'MMACHC',
 546: 'HMGB1P48',
 547: 'PRKAA2',
 548: 'C8A',
 549: 'AL161740.1',
 550: 'DAB1-AS1',
 551: 'IL12RB2',
 552: 'LINC01702',
 553: 'ANGPTL3',
 554: 'AL138847.2',
 555: 'AC103923.1',
 556: 'ATG4C',
 557: 'AC099794.1',
 558: 'DMRTB1',
 559: 'AL049745.1',
 560: 'DIO1',
 561: 'LRRC42',
 562: 'TCEANC2',
 563: 'EPHB2',
 564: 'KDM1A',
 565: 'AL161672.1',
 566: 'DEPDC1-AS1',
 567: 'LINC01707',
 568: 'LRRC7',
 569: 'FOXD3',
 570: 'ALG6',
 571: 'EFCAB7',
 572: 'DLEU2L',
 573: 'AL583808.2',
 574: 'KRT8P21',
 575: 'LINC01360',
 576: 'LINC02238',
 577: 'IQCC',
 578: 'DCDC2B',
 579: 'EIF3I',
 580: 'FAM167B',
 581: 'LCK',
 582: 'PDCL3P6',
 583: 'ANAPC10P1',
 584: 'AL513218.1',
 585: 'PLA2G12AP1',
 586: 'PRPF38A',
 587: 'AL354872.2',
 588: 'AL354872.1',
 589: 'LINC01788',
 590: 'AL031429.1',
 591: 'ZRANB2-AS1',
 592: 'MSH4',
 593: 'AC092813.1',
 594: 'AC092813.2',
 595: 'ST6GALNAC3',
 596: 'CDC42',
 597: 'CDC42-IT1',
 598: 'AL031281.2',
 599: 'ZBTB40',
 600: 'RNF11',
 601: 'TTC39A-AS1',
 602: 'AL671986.1',
 603: 'AC104458.1',
 604: 'TPI1P1',
 605: 'ST6GALNAC5',
 606: 'ZMYM1',
 607: 'EFCAB14P1',
 608: 'ZMYM4',
 609: 'ZRANB2-AS2',
 610: 'AL359821.1',
 611: 'GDI2P2',
 612: 'RPL31P12',
 613: 'AL035409.1',
 614: 'AC113935.1',
 615: 'AC093433.1',
 616: 'AK5',
 617: 'MGC27382',
 618: 'PTGFR',
 619: 'IFI44L',
 620: 'IFI44',
 621: 'HMGB1P18',
 622: 'AL596276.2',
 623: 'LINC01781',
 624: 'MTND2P30',
 625: 'AL357632.1',
 626: 'TMEM125',
 627: 'TIE1',
 628: 'MPL',
 629: 'CDC20',
 630: 'AL139289.1',
 631: 'AC104837.1',
 632: 'ADH5P2',
 633: 'AL445685.1',
 634: 'BTF3L4',
 635: 'ZFYVE9',
 636: 'RN7SL788P',
 637: 'CDCA8',
 638: 'ACTN4P2',
 639: 'MANEAL',
 640: 'C1orf122',
 641: 'AL359504.1',
 642: 'AL450063.1',
 643: 'SAMD13',
 644: 'NIPAL3',
 645: 'RCAN3',
 646: 'NCMAP',
 647: 'AL445686.1',
 648: 'SRRM1',
 649: 'RAVER2',
 650: 'AL606517.1',
 651: 'AK4',
 652: 'AC104455.1',
 653: 'CLCA2',
 654: 'CLCA1',
 655: 'CLCA4',
 656: 'AL445991.1',
 657: 'AC099063.4',
 658: 'AC099063.1',
 659: 'BX119321.1',
 660: 'GBP6',
 661: 'FPGT',
 662: 'FPGT-TNNI3K',
 663: 'TNNI3K',
 664: 'AC105271.1',
 665: 'ERICH3-AS1',
 666: 'AL353898.1',
 667: 'AL357673.2',
 668: 'MRPL37',
 669: 'SSBP3-AS1',
 670: 'LINC01763',
 671: 'RPL5P6',
 672: 'FEN1P1',
 673: 'KPNA6',
 674: 'TXLNA',
 675: 'CCDC28B',
 676: 'AC104170.2',
 677: 'AC104170.1',
 678: 'OSBPL9',
 679: 'SLC25A6P3',
 680: 'AL050343.1',
 681: 'LPCAT2BP',
 682: 'BTBD8',
 683: 'AC104836.1',
 684: 'PRKAR1AP1',
 685: 'ZBTB8B',
 686: 'ZBTB8A',
 687: 'RBBP4',
 688: 'KIAA1522',
 689: 'MED18',
 690: 'PHACTR4',
 691: 'CR391992.1',
 692: 'RNU6ATAC27P',
 693: 'RCC1',
 694: 'RN7SL62P',
 695: 'ZYG11B',
 696: 'ZYG11A',
 697: 'AC099677.1',
 698: 'AC119800.1',
 699: 'PDE4B',
 700: 'SGIP1',
 701: 'TCTEX1D1',
 702: 'AL049796.1',
 703: 'AC093579.1',
 704: 'AC097059.1',
 705: 'GAPDHP29',
 706: 'KCNQ4',
 707: 'AC119677.1',
 708: 'CTPS1',
 709: 'AL683887.1',
 710: 'AC099566.1',
 711: 'RNU1-130P',
 712: 'AC092393.1',
 713: 'UBE2WP1',
 714: 'GADD45A',
 715: 'GNG12-AS1',
 716: 'AL157407.1',
 717: 'AL138789.1',
 718: 'RPL26P9',
 719: 'AC114878.1',
 720: 'NFU1P2',
 721: 'MIER1',
 722: 'IL23R',
 723: 'AL389925.1',
 724: 'PALMD',
 725: 'HMGB3P10',
 726: 'SCP2',
 727: 'MIR1273F',
 728: 'MIR1273G',
 729: 'ADGRL2',
 730: 'HNRNPA3P14',
 731: 'AL138799.1',
 732: 'CDC7',
 733: 'HSP90B3P',
 734: 'BRDT',
 735: 'EPHX4',
 736: 'RLF',
 737: 'TMCO2',
 738: 'ZMPSTE24',
 739: 'SMAP2',
 740: 'TMEM56-RWDD3',
 741: 'AC092802.3',
 742: 'RWDD3',
 743: 'LINC01761',
 744: 'AL356479.1',
 745: 'LINC00853',
 746: 'AL135960.1',
 747: 'CMPK1',
 748: 'FOXE3',
 749: 'AL109741.2',
 750: 'LINC01307',
 751: 'LINC01709',
 752: 'AL356280.1',
 753: 'TYW3',
 754: 'LHX8',
 755: 'AC093156.1',
 756: 'AMY2A',
 757: 'AL357134.1',
 758: 'MDS2',
 759: 'AL451000.1',
 760: 'RPL11',
 761: 'AL355306.2',
 762: 'LINC01661',
 763: 'PRMT6',
 764: 'NTNG1',
 765: 'AC093157.1',
 766: 'AC119501.1',
 767: 'S1PR1',
 768: 'AL359258.3',
 769: 'SLC25A24P1',
 770: 'AC114491.1',
 771: 'VAV3-AS1',
 772: 'AL390036.1',
 773: 'AL359258.2',
 774: 'ST13P20',
 775: 'LINC01362',
 776: 'LINC01712',
 777: 'AL035706.1',
 778: 'PRKACB',
 779: 'MIGA1',
 780: 'NSRP1P1',
 781: 'DNASE2B',
 782: 'RPF1',
 783: 'SPATA1',
 784: 'WDR63',
 785: 'Y_RNA',
 786: 'AL078459.1',
 787: 'AL360219.1',
 788: 'CYR61',
 789: 'SNORD81',
 790: 'RPS15AP7',
 791: 'L1TD1',
 792: 'USP1',
 793: 'MTCO1P12',
 794: 'MTCO2P12',
 795: 'MTATP8P1',
 796: 'MTATP6P1',
 797: 'MTCO3P12',
 798: 'CAPNS1P1',
 799: 'GBP1P1',
 800: 'LRRC8B',
 801: 'AC093423.2',
 802: 'LRRC8C',
 803: 'DNAJA1P5',
 804: 'AC095032.2',
 805: 'RNPC3',
 806: 'AMY2B',
 807: 'RPL7P8',
 808: 'GSTM4',
 809: 'GSTM2',
 810: 'GSTM1',
 811: 'GSTM5',
 812: 'OR11I1P',
 813: 'CD53',
 814: 'AL360270.1',
 815: 'AL360270.3',
 816: 'PIFO',
 817: 'HIGD1AP12',
 818: 'UBE2FP3',
 819: 'Y_RNA',
 820: 'AL355488.2',
 821: 'PROK1',
 822: 'AL358215.2',
 823: 'AL358215.3',
 824: 'CYMP',
 825: 'AC093155.1',
 826: 'LINC01140',
 827: 'AC099062.1',
 828: 'LMO4',
 829: 'HSPE1P25',
 830: 'NEXN',
 831: 'DNAJB4',
 832: 'GIPC2',
 833: 'AC103591.1',
 834: 'SZT2',
 835: 'HYI-AS1',
 836: 'PTPRF',
 837: 'KDM4A',
 838: 'RPL12P13',
 839: 'TRNP1',
 840: 'AL590640.2',
 841: 'NPM1P39',
 842: 'RANP5',
 843: 'TMEM167B',
 844: 'KIAA1324',
 845: 'IPO13',
 846: 'DPH2',
 847: 'ATP6V0B',
 848: 'B4GALT2',
 849: 'CCDC24',
 850: 'NR1H5P',
 851: 'SYCP1',
 852: 'TSHB',
 853: 'AC093019.1',
 854: 'TRMT13',
 855: 'RPL23AP90',
 856: 'BRI3P1',
 857: 'AL445928.1',
 858: 'PGM1',
 859: 'RN7SL130P',
 860: 'ROR1',
 861: 'UBE2U',
 862: 'CACHD1',
 863: 'AL136455.1',
 864: 'AC092506.1',
 865: 'CDK4P1',
 866: 'SEPT2P1',
 867: 'AL512844.1',
 868: 'AL512638.2',
 869: 'AL512638.1',
 870: 'ELOCP20',
 871: 'CNOT7P2',
 872: 'AL354702.1',
 873: 'AL139260.1',
 874: 'RNU6-605P',
 875: 'AKIRIN1',
 876: 'NDUFS5',
 877: 'AL033527.2',
 878: 'MFSD2A',
 879: 'AL663070.1',
 880: 'CAP1',
 881: 'AL512599.1',
 882: 'PLK3',
 883: 'HSD3B2',
 884: 'HSD3BP2',
 885: 'HSD3BP1',
 886: 'HSD3B1',
 887: 'HSD3BP3',
 888: 'STRIP1',
 889: 'AL160006.1',
 890: 'LINC01397',
 891: 'UBL4B',
 892: 'SLC6A17',
 893: 'MACF1',
 894: 'AL356055.1',
 895: 'BMP8A',
 896: 'OXCT2P1',
 897: 'AL365277.2',
 898: 'AL035410.2',
 899: 'AL035410.1',
 900: 'EIF2S2P5',
 901: 'PKMP1',
 902: 'NBPF26',
 903: 'PPIAL4A',
 904: 'LINC00623',
 905: 'EEF1A1P11',
 906: 'PTBP2',
 907: 'DPYD-AS1',
 908: 'SEC63P1',
 909: 'AC244021.2',
 910: 'AL592494.2',
 911: 'EMBP1',
 912: 'AC244669.2',
 913: 'NBPF8',
 914: 'AC239859.1',
 915: 'PFN1P12',
 916: 'LINC01776',
 917: 'SNX7',
 918: 'AL445433.2',
 919: 'AL445433.1',
 920: 'PLPPR4',
 921: 'WARS2-IT1',
 922: 'AL359915.2',
 923: 'LINC01780',
 924: 'HAO2',
 925: 'AC239800.2',
 926: 'AC239800.1',
 927: 'FAM91A3P',
 928: 'AC239800.3',
 929: 'AC241585.1',
 930: 'AC239799.2',
 931: 'FP700111.1',
 932: 'FP700107.1',
 933: 'FAM72D',
 934: 'LINC01750',
 935: 'TXNP3',
 936: 'CTTNBP2NL',
 937: 'AL139424.2',
 938: 'PGD',
 939: 'CENPS-CORT',
 940: 'CENPS',
 941: 'CORT',
 942: 'AC114488.3',
 943: 'AL136115.1',
 944: 'KHDRBS1',
 945: 'TMEM39B',
 946: 'PPIH',
 947: 'AC098484.2',
 948: 'YBX1',
 949: 'C1orf50',
 950: 'AC098484.3',
 951: 'PDE4DIPP1',
 952: 'ABHD17AP1',
 953: 'AC239803.1',
 954: 'AC245100.6',
 955: 'AC245100.1',
 956: 'GPR89A',
 957: 'HYDIN2',
 958: 'NBPF12',
 959: 'AC244394.1',
 960: 'GPR89B',
 961: 'AC239803.2',
 962: 'AC239803.3',
 963: 'AC245100.8',
 964: 'U1',
 965: 'RAD54L',
 966: 'UQCRH',
 967: 'NSUN4',
 968: 'AL122001.1',
 969: 'FAAH',
 970: 'AC104836.2',
 971: 'AL663109.1',
 972: 'C1orf146',
 973: 'RPAP2',
 974: 'AC104332.1',
 975: 'AC245100.4',
 976: 'RNVU1-3',
 977: 'AC245100.2',
 978: 'AL449283.1',
 979: 'MTF2',
 980: 'CCDC18',
 981: 'HIST2H4A',
 982: 'AC239868.1',
 983: 'AC239868.4',
 984: 'AC244453.1',
 985: 'SRGAP2C',
 986: 'AC244021.1',
 987: 'CEPT1',
 988: 'CHI3L2',
 989: 'CHIAP1',
 990: 'CHIAP2',
 991: 'CHIA',
 992: 'HSD3BP4',
 993: 'PHGDH',
 994: 'PFN1P9',
 995: 'RTCA',
 996: 'CDC14A',
 997: 'GPR88',
 998: 'BCL9',
 999: 'AC241644.2',
 ...}